import { useState, useCallback } from 'react';
import { Language, Translation } from '../types';

const translations: Record<Language, Translation> = {
  [Language.EN]: {
    productName: 'AI Personal Finance Assistant',
    readyPrompt: 'Tap the mic and describe your expense',
    listening: 'Listening...',
    processing: 'Processing your expense...',
    confirmAndSync: 'Confirm & Sync',
    discard: 'Discard',
    syncComplete: 'Sync Complete.',
    errorOccurred: 'An error occurred. Please try again.',
    amount: 'Amount',
    date: 'Date',
    category: 'Category',
    note: 'Note / Merchant',
    categories: 'Categories',
    manageCategories: 'Manage Categories',
    addCategory: 'Add',
    newCategory: 'New category name',
    micPermissionDenied: 'Microphone access denied. Click the 🔒 icon in the address bar to allow it.',
    micStartError: 'Could not start microphone. Please check device and permissions.',
    dashboardTitle: 'Expense Dashboard',
    totalExpenses: 'Total Expenses',
    noExpenses: 'No expenses recorded yet.',
    saveChanges: 'Save Changes',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    youSaid: 'You said',
    agentResponse: 'Agent Response',
    settings: 'Settings',
    audioQuality: 'Audio Quality',
    standard: 'Standard',
    high: 'High',
    aiVoice: 'AI Voice',
    wakeWord: 'Wake Word',
    wakeWordDescription: 'Listen for "Hey Assistant" to start recording.',
    listeningForWakeWord: 'Listening for "Hey Assistant"...',
    dateHeaders: {
      today: 'Today',
      yesterday: 'Yesterday',
      thisWeek: 'This Week',
      thisMonth: 'This Month',
      older: 'Older',
    },
    defaultCategories: {
      food: 'Food & Dining',
      transport: 'Transportation',
      entertainment: 'Entertainment',
      utilities: 'Utilities',
      rent: 'Rent',
      shopping: 'Shopping',
      wellness: 'Wellness',
      other: 'Other',
    },
  },
  [Language.ZH_TW]: {
    productName: 'AI 個人理財助理',
    readyPrompt: '點擊麥克風開始描述您的支出',
    listening: '正在聆聽...',
    processing: '正在處理您的支出...',
    confirmAndSync: '確認並同步',
    discard: '捨棄',
    syncComplete: '同步完成',
    errorOccurred: '發生錯誤，請重試。',
    amount: '金額',
    date: '日期',
    category: '類別',
    note: '備註 / 商家',
    categories: '支出類別',
    manageCategories: '管理類別',
    addCategory: '新增',
    newCategory: '新類別名稱',
    micPermissionDenied: '麥克風權限被拒。請點擊網址列的 🔒 圖示以允許存取。',
    micStartError: '無法啟動麥克風。請檢查您的設備與權限設定。',
    dashboardTitle: '支出儀表板',
    totalExpenses: '總支出',
    noExpenses: '尚未記錄任何支出。',
    saveChanges: '儲存變更',
    theme: '主題',
    light: '淺色',
    dark: '深色',
    system: '系統',
    youSaid: '您說',
    agentResponse: '助理回覆',
    settings: '設定',
    audioQuality: '音訊品質',
    standard: '標準',
    high: '高',
    aiVoice: 'AI 語音',
    wakeWord: '喚醒詞',
    wakeWordDescription: '聆聽「你好助理」以開始錄音。',
    listeningForWakeWord: '正在等待喚醒詞「你好助理」...',
    dateHeaders: {
      today: '今天',
      yesterday: '昨天',
      thisWeek: '本週',
      thisMonth: '本月',
      older: '更早',
    },
    defaultCategories: {
      food: '餐飲',
      transport: '交通',
      entertainment: '娛樂',
      utilities: '水電瓦斯',
      rent: '租金',
      shopping: '購物',
      wellness: '健康',
      other: '其他',
    },
  },
};

export const useLocalization = () => {
  const [language, setLanguage] = useState<Language>(Language.ZH_TW);

  const setLang = useCallback((lang: Language) => {
    setLanguage(lang);
  }, []);

  const t = translations[language];

  return { language, setLanguage: setLang, t };
};